import os
import sys
from pathlib import Path

import requests
from dotenv import load_dotenv
from ruamel.yaml import YAML
from ruamel.yaml.comments import CommentedMap

load_dotenv()

PROFILE_DIR = Path(__file__).resolve().parent.parent / "profile"
REPOS_YAML = PROFILE_DIR / "repos.yaml"
CATEGORY_MD = PROFILE_DIR / "CATEGORY.md"

UNCATEGORIZED = "未分類"
META_GROUP = "管理"
CATEGORY_HEADER = "<!-- This file is generated by scripts/generate_profile_readme.py. Do not edit manually. -->"

yaml = YAML()
yaml.preserve_quotes = True
yaml.indent(mapping=2, sequence=4, offset=2)


def load_config():
    return yaml.load(REPOS_YAML.read_text(encoding="utf-8"))


def iter_categories(config):
    for group in config["groups"]:
        for category in group["categories"]:
            yield category


def listed_names(config):
    names = set()
    for category in iter_categories(config):
        for repo in category["repos"] or []:
            names.add(str(repo["name"]).lower())
    return names


def fetch_org_repos(org, token):
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
    }
    repos = []
    page = 1
    while True:
        url = f"https://api.github.com/orgs/{org}/repos?per_page=100&page={page}"
        response = requests.get(url, headers=headers, timeout=30)
        response.raise_for_status()
        data = response.json()
        if not data:
            break
        repos.extend(repo["name"] for repo in data)
        page += 1
    return repos


def uncategorized_category(config):
    for category in iter_categories(config):
        if category.get("name") == UNCATEGORIZED:
            return category

    meta_group = None
    for group in config["groups"]:
        if group["name"] == META_GROUP:
            meta_group = group
            break
    if meta_group is None:
        meta_group = CommentedMap()
        meta_group["name"] = META_GROUP
        meta_group["categories"] = []
        config["groups"].append(meta_group)

    category = CommentedMap()
    category["name"] = UNCATEGORIZED
    category["repos"] = []
    meta_group["categories"].append(category)
    return category


def add_repo(category, name):
    entry = CommentedMap()
    entry["name"] = name
    entry["memo"] = ""
    entry.fa.set_flow_style()
    category["repos"].append(entry)


def sync_with_org(config, org_repos):
    listed = listed_names(config)
    new_repos = sorted(name for name in org_repos if name.lower() not in listed)

    if new_repos:
        category = uncategorized_category(config)
        for name in new_repos:
            add_repo(category, name)
        print(f"Added {len(new_repos)} new repo(s) to {UNCATEGORIZED}: {', '.join(new_repos)}")

    org_lower = {name.lower() for name in org_repos}
    for category in iter_categories(config):
        for repo in category["repos"] or []:
            if str(repo["name"]).lower() not in org_lower:
                print(f"WARNING: '{repo['name']}' is listed but not found in org (not removed)")

    return new_repos


def render_category(category, org):
    repos = category["repos"] or []
    if not repos:
        return None
    lines = []
    if not category.get("flat"):
        lines.extend([f"### {category['name']}", ""])
    lines.extend([
        "| Repository | Repository URL | Memo |",
        "| --- | --- | --- |",
    ])
    for repo in repos:
        name = repo["name"]
        memo = repo.get("memo") or ""
        url = f"https://github.com/{org}/{name}"
        lines.append(f"| `{name}` | [GitHub]({url}) | {memo} |")
    return "\n".join(lines)


def render_tables(config, org):
    blocks = []
    for group in config["groups"]:
        category_blocks = [
            block
            for category in group["categories"]
            if (block := render_category(category, org)) is not None
        ]
        if not category_blocks:
            continue
        header = f"## {group['name']}"
        description = group.get("description")
        if description:
            header = f"{header}\n\n{description}"
        blocks.append("\n\n".join([header, *category_blocks]))
    return "\n\n".join(blocks)


def build_category_md(generated):
    return f"{CATEGORY_HEADER}\n\n{generated}\n"


def dump_yaml(config):
    from io import StringIO

    stream = StringIO()
    yaml.dump(config, stream)
    return stream.getvalue()


def write_github_output(changed, new_repos_added):
    output_path = os.getenv("GITHUB_OUTPUT")
    if not output_path:
        return
    with open(output_path, "a", encoding="utf-8") as handle:
        handle.write(f"changed={'true' if changed else 'false'}\n")
        handle.write(f"new_repos_added={'true' if new_repos_added else 'false'}\n")


def main():
    check_only = "--check" in sys.argv

    config = load_config()
    org = config.get("org", "lvncerpedia")
    new_repos = []

    token = os.getenv("GITHUB_TOKEN")
    if token:
        org_repos = fetch_org_repos(org, token)
        print(f"Fetched {len(org_repos)} repos from org '{org}'")
        new_repos = sync_with_org(config, org_repos)
    else:
        print("No GITHUB_TOKEN: skipping org sync, rendering from repos.yaml only")

    new_repos_added = bool(new_repos)
    new_yaml = dump_yaml(config)
    new_category = build_category_md(render_tables(config, org))

    current_yaml = REPOS_YAML.read_text(encoding="utf-8")
    current_category = CATEGORY_MD.read_text(encoding="utf-8") if CATEGORY_MD.exists() else ""
    category_changed = new_category != current_category
    yaml_changed_by_sync = new_repos_added and new_yaml != current_yaml
    changed = category_changed or yaml_changed_by_sync

    if check_only:
        if changed:
            print("CHECK FAILED: repos.yaml or CATEGORY.md is out of date. Run the generator.")
            write_github_output(changed, new_repos_added)
            sys.exit(1)
        print("CHECK OK: profile is up to date")
        write_github_output(False, False)
        return

    if not changed:
        print("No changes")
        write_github_output(False, False)
        return

    if new_repos_added:
        REPOS_YAML.write_text(new_yaml, encoding="utf-8")
    if category_changed:
        CATEGORY_MD.write_text(new_category, encoding="utf-8")

    write_github_output(changed, new_repos_added)
    print("Updated repos.yaml and CATEGORY.md" if new_repos_added else "Updated CATEGORY.md")


if __name__ == "__main__":
    main()
